name: "Update Profile"
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup git environment
        run: |
         git config --global user.email "contact.reallyfatyoshi@gmail.com" 
         git config --global user.name "ReallyFatYoshi"

      - name: Run script
        run: npm run start

      - name: Git push
        run: |
          git add --all
          git commit -m "Updated readme.md"
          git push -u origin main